******************************************************************
 
Info  : Starting CT Translator 
Info  : HyperWorks Version 2019.1.0.20 
Info  : Using CT Library Version 2018-SP3-02 
Info  : Reading file C:/Users/raghe/Google Drive (s265776polito@gmail.com)/M2/Spring/Car Body Design & Aerodynamics/Car Body Design/Exercise/Exercise 2/CrossCLongC.SLDPRT on 04-25-2020 21:53:20 
Info  : Using C:\Program Files\Altair\2019\io\afc_translators\bin\win64\ct\ct_reader.dll 
 
Options explicitly set by user 
		AvoidPartAttributes  =  off 
		CleanupTol  =  -0.01 
		CreationType  =  Parts 
		DoNotMergeEdges  =  off 
		ImportBlanked  =  off 
		SplitComponents  =  Part 
		TargetUnits  =  CAD units 
 
Options from INI file 
		AvoidThirdPartyConversion  =  on 
		DensityAsMetadata  =  on 
		ImportCoordinateSystems  =  on 
		ImportFreeCurves  =  on 
		ImportFreePoints  =  on 
		MID  =  MaterialId 
		MaterialName  =  Material 
		MeshFlag  =  MeshFlag 
		OriginalIdAsMetadata  =  on 
		PID  =  PID 
		PartNumber  =  PartNumber 
		Revision  =  Revision 
		SplitPeriodicFaces  =  on 
		TagsAsMetadata  =  on 
		ThicknessName  =  Thickness 
		UID  =  UUID:UUID 
 
Info  : CT License Key  = altair%0ul209c301av1ane137c0dsu16f217tq01jj062p137c08os1ba80hd517ov0hd5180w11uz19tl04id180w0wz819tl0wz81ba8 
Info  : CT License Key Initialization Completed Successfully 
Info  : Using Parasolid Kernel Version V30.0.185 
Reading  C:\Users\raghe\Google Drive (s265776polito@gmail.com)\M2\Spring\Car Body Design & Aerodynamics\Car Body Design\Exercise\Exercise 2\CrossCLongC.SLDPRT 

******************************************************************
 
